spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seatingArrangements?serverTimezone=UTC
    username: root
    password: g^9sfWpM+k3Eg/s
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
